### PR TITLE
added testing instructions

### PR DESCRIPTION
**Pull request by ab7289**
Added some directives for logging in and testing. Please let me know what additional things we should add.

### CODE REVIEW

**Comment by ab7289** [comment]
> * Sign Up for an account (you need 2 accounts to test the entire functionality).
> * Login
> * Search for a location (e.g. based on street address, zipcode etc.). Searching based on zipcode should also display general complaint levels for that zipcode.
> * The search page displays different locations along with the number of apartments at each location that satisfy your selected criteria. Click on a particular location to see all the apartments at that location. You can also display them on a map to get a better idea of the neighborhood.
> * You can favorite a particular location and then go to the "Favorites" tab on the navigation bar to see your favorites list. You can remove an apartment from favorites as well.
> * You can also leave a review for a particular location and it should display in your account page (accessible from "My account" on the navigation bar) and under that location's reviews.
> * Next, try to upload your apartment. You can find this apartment under your account view.
> * Next, try to search for some location and go to some apartment inside that location, setting yourself as the landlord (by clicking on the "Are you a tenant or landlord.....?"). For now, it does not do any validation and automatically sets you up as the tenant/landlord.
> * In order to be able to contact the landlord for an apartment that you are interested in, you can find an apartment that already has a landlord. However, this might not be easy to find since most of our data is coming from Craigslist and Zillow and we don't have the landlords for those apartments set up. Since we don't allow the landlord to contact the landlord (himself/herself), you would need to logout and login from the other account that you created in order to send the landlord a message by going to the apartment view and clicking on the "Interested?" button.

Great suggestions, thanks! It's been a long day so the suggested edits are appreciated.

**Comment by mok232** [comment]
Yeah no worries. I can imagine. LGTM!

**Comment by ab7289** [comment]
I'm going to leave this PR open until the morning so people can continue to contribute their thoughts. Since this won't conflict with any other changes It can be merged in right before testing day starts.

**Comment by mok232** [comment]
Good idea!

**Pull request merged**
