### PR TITLE
311 Statistics and Complaints Styling

### LINKED ISSUE #333: 311 Complaints
**User story**

As a user I want the 311 complaints to be displayed more prominently and with better UX.

**Acceptance criteria**

**Definition of Done**

In the search page, instead of displaying complaints level as a small progress bar, maybe show them as a color backed card in the upper right hand corner of the body (shrink the search form down a bit). 
- lots of complaints = red backing
- few complaints = green backing

See More?
- instead of redirecting to a new page, display as a modal or, even better, display as a pull out panel from the right side of the screen.

Apartments View
- pull the zipcode from the current apartment and use it to display the 311 complaint data as a color backed card

### PR DESCRIPTION
**Pull request by mok232**
This PR closes #333 

- Adds 311 noise and parking complaints statistics to the apartment detail page
- For the statistics cards in the apartment page, the card is displayed with a red background if the complaint level is >2 or green otherwise.
- I tried other design formats for the cards (e.g. horizontal under the image but the image appeared shrunk which was not ideal). I also tried making a revealable card but it turned out to be rather difficult to merge the 2 different stylesheets. 
- Finally, I resized the images within the card and made the cards scrollable so that it doesn't take up too much space.
- Added a button "311 Complaints" that directs to a new page with the complaints styled as cards and paginated.
- Closed complaints are displayed in a green background whereas others are displayed in a red background.

### CODE REVIEW

**Comment by ab7289** [comment]
@mok232, So i just took a short glance now, and I think overall these look really good. I have some minor comments though. 

For one, it appears that each of the cards has a small second of at the bottom that is empty (Pic below). Could we just remove that part of the card if it's not being used for anything? I think it would help reduce the size of the cards a bit and reduce unneeded space.

Screen Shot 2019-12-09 at 8 56 29 PM

Also maybe instead of having the 311 complaints button under the Interested? button, which feels like awkward placing to me, could we just make the entire card a hyper link to the 311 complaints?

Lastly, I know you're probably sick of looking at the cards, but could they be shrunk down just a bit? They kinda dwarf everything else in the page.

Overall looking great!

**Comment by mok232** [comment]
@ab7289 Good catch regarding the extra space at the bottom of the cards.

Also, I really like the idea of making the cards into a hyperlink. So both cards should point to the same page. Right?

Regarding reducing the card size, I am thinking of 2 options:
1). Reducing the empty lines within in the card, or
2). Changing the page design to a 2-column format. The left column would display the apartment image(s), under which we would display the apartment description, which would allow us slightly more space for the description text per row. The right column would contain the statistics cards.

image

Let me know what you think?

**Comment by ab7289** [comment]
> @ab7289 Good catch regarding the extra space at the bottom of the cards.
> 
> Also, I really like the idea of making the cards into a hyperlink. So both cards should point to the same page. Right?
> 
> Regarding reducing the card size, I am thinking of 2 options:
> 1). Reducing the empty lines within in the card, or
> 2). Changing the page design to a 2-column format. The left column would display the apartment image(s), under which we would display the apartment description, which would allow us slightly more space for the description text per row. The right column would contain the statistics cards.
> 
> image
> 
> Let me know what you think?

@mok232 , Yes, both cards would link to the same page in this case.

I like option 2 better, but I would also be fine if we just reduced the x,y dimension of the card a bit and keep the proportions otherwise the same.

**Comment by mok232** [comment]
Changed apartment page design to a 3-column format
1) `col-sm-6` Apt Image + Description
2) `col-sm-3` Noise Complaints Card
3) `col-sm-3` Parking Complaints Card

Also reduced the card size by removing extra margins between the `<div>` and `<p>` tags within the card. Improved test coverage.

image

**Comment by ab7289** [comment]
@mok232 I like the updates! I did notice one small bug in the complaints page.  Once of the addresses was displayed as NaN, would it be possible to display as N/A instead?

This was found in the complaints data for 10005. The date was 2019-12-05 and Descriptor was APS.

Screen Shot 2019-12-10 at 10 14 27 AM

**Comment by mok232** [comment]
@ab7289 Good catch! Added checks for all the fields so they display as "N/A" instead of nan.

**Pull request merged**
